name_maximum: 50
email_maximum: 255
password_from: 6
password_to: 12
phone_number_maximum: 12
phone_number_minimum: 10
address_maximum: 255
address_minimum: 20
per_page_products: 9
price_greater: 0
price_less: 1000000
file_accept: "image/jpeg,image/gif,image/png"
file_accept_excel: "file/xlsx"
file_valid: ["image/jpeg", "image/gif", "image/png"]
per_page: 12
per_page_user: 9
per_page_purchase: 9
image_display: 200
format_xls: "xls"
excel: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
string_view: 100
string_admin: 20
string_purchase: 30
