name_maximum: 50
email_maximum: 255
password_from: 6
password_to: 12
phone_number_maximum: 11
phone_number_minimum: 10
address_maximum: 255
address_minimum: 20
per_page_products: 9
price_greater: 0
price_less: 1000000
file_accept: "image/jpeg,image/gif,image/png"
file_valid: ["image/jpeg", "image/gif", "image/png"]
per_page: 12
per_page_user: 9
image_display: 200
